###/login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "tester01",
    "password": "GteteqbQQgSr88SwNExUQv2ydb7xuf8c"
}


### /clinets 
GET  http://localhost:3000/api/clients
Content-Type: application/json
x-user-auth:{"username":"tester01","token":"3cc16d27d89a63d2306494eb9e44b821"}


###/new client
POST http://localhost:3000/api/client/new
Content-Type: application/json
x-user-auth:{"username":"tester01","token":"958d99ed9ce7f92ac0cedc4eb84bfe6d"}

{
    "name": "Ellen Berhane",
    "email": "ellen.berhane@example.com",
    "telephone": "070 564 0001"
}


###/ client
DELETE  http://localhost:3000/api/client/5
Content-Type: application/json
x-user-auth:{"username":"tester01","token":"3824d63721707869eae2d0188007ae71"}


### /Get a Client by ID
GET http://localhost:3000/api/client/1
Content-Type: application/json
x-user-auth: {"username":"tester01","token":"442a043c753baab9b80144f1da0f9a30"}


###/ Delete Client Without Authorization
DELETE http://localhost:3000/api/client/4
Content-Type: application/json
x-user-auth: {"username":"invalidUser","token":"442a043c753baab9b80144f1da0f9a30"}

###/ Delete Client Without Authorization
DELETE http://localhost:3000/api/client/5
Content-Type: application/json
x-user-auth: {"username":"invalidUser","token":"6683b8c1266c78612dbe99ed2367c647"}'


